create table if not exists public.sent_mail_history (
  id bigint generated by default as identity primary key,
  recipient_email text not null,
  recipient_name text,
  sent_at timestamptz not null default now()
);

create index if not exists sent_mail_history_email_idx
  on public.sent_mail_history (lower(recipient_email));

alter table public.sent_mail_history enable row level security;
